var platforms = require('./platforms');
var actions = require('./actions');

var parse = function (action, platform, response) {
  
  if (!action || !platform || !response) {
    console.log('ERROR: Missing parameter in parse function');
    return null;
  } else if (actions.indexOf(action) === -1) {
    console.log('ERROR: Invalid action parameter in parse function');
    return null;
  } else if (!platforms.hasOwnProperty(platform)) {
    console.log('ERROR: Platform is not defined in parse function');
    return null;
  } else if (!platforms[platform].parsers.hasOwnProperty(action)) {
    console.log('ERROR: Action is not defined for this platform in parse function');
    return null;
  }
  
  return platforms[platform].parsers[action](response);
};

module.exports = parse;


// { id: 14405828,
//   name: 'doproxy',
//   memory: 1024,
//   vcpus: 1,
//   disk: 30,
//   locked: false,
//   status: 'active',
//   kernel: null,
//   created_at: '2016-04-30T05:35:04Z',
//   features: [ 'private_networking', 'virtio' ],
//   backup_ids: [],
//   next_backup_window: null,
//   snapshot_ids: [],
//   image: 
//    { id: 16539246,
//      name: 'LAMP on 14.04',
//      distribution: 'Ubuntu',
//      slug: 'lamp',
//      public: true,
//      regions: 
//       [ 'nyc1',
//         'sfo1',
//         'nyc2',
//         'ams2',
//         'sgp1',
//         'lon1',
//         'nyc3',
//         'ams3',
//         'fra1',
//         'tor1',
//         'sfo2' ],
//      created_at: '2016-03-30T21:44:25Z',
//      min_disk_size: 20,
//      type: 'snapshot',
//      size_gigabytes: 1.86 },
//   drives: [],
//   size: 
//    { slug: '1gb',
//      memory: 1024,
//      vcpus: 1,
//      disk: 30,
//      transfer: 2,
//      price_monthly: 10,
//      price_hourly: 0.01488,
//      regions: 
//       [ 'ams1',
//         'ams2',
//         'ams3',
//         'fra1',
//         'lon1',
//         'nyc1',
//         'nyc2',
//         'nyc3',
//         'sfo1',
//         'sgp1',
//         'tor1' ],
//      available: true },
//   size_slug: '1gb',
//   networks: { v4: [ [Object], [Object] ], v6: [] },
//   region: 
//    { name: 'San Francisco 1',
//      slug: 'sfo1',
//      sizes: [ '32gb', '16gb', '2gb', '1gb', '4gb', '8gb', '512mb', '64gb', '48gb' ],
//      features: [ 'private_networking', 'backups', 'ipv6', 'metadata' ],
//      available: true },
//   tags: [] }
// { id: 14410247,
//   name: 'mean-spawn-0',
//   memory: 512,
//   vcpus: 1,
//   disk: 20,
//   locked: false,
//   status: 'active',
//   kernel: 
//    { id: 5175,
//      name: 'Ubuntu 14.04 x64 vmlinuz-3.13.0-57-generic',
//      version: '3.13.0-57-generic' },
//   created_at: '2016-04-30T07:24:19Z',
//   features: [ 'private_networking', 'virtio' ],
//   backup_ids: [],
//   next_backup_window: null,
//   snapshot_ids: [],
//   image: 
//    { id: 17075455,
//      name: 'mean-spawn-1-1462000309694',
//      distribution: 'Ubuntu',
//      slug: null,
//      public: false,
//      regions: [ 'sfo1' ],
//      created_at: '2016-04-30T07:12:18Z',
//      min_disk_size: 20,
//      type: 'snapshot',
//      size_gigabytes: 5.9 },
//   drives: [],
//   size: 
//    { slug: '512mb',
//      memory: 512,
//      vcpus: 1,
//      disk: 20,
//      transfer: 1,
//      price_monthly: 5,
//      price_hourly: 0.00744,
//      regions: 
//       [ 'ams1',
//         'ams2',
//         'ams3',
//         'fra1',
//         'lon1',
//         'nyc1',
//         'nyc2',
//         'nyc3',
//         'sfo1',
//         'sgp1',
//         'tor1' ],
//      available: true },
//   size_slug: '512mb',
//   networks: { v4: [ [Object], [Object] ], v6: [] },
//   region: 
//    { name: 'San Francisco 1',
//      slug: 'sfo1',
//      sizes: [ '32gb', '16gb', '2gb', '1gb', '4gb', '8gb', '512mb', '64gb', '48gb' ],
//      features: [ 'private_networking', 'backups', 'ipv6', 'metadata' ],
//      available: true },
//   tags: [] }
// { id: 14410543,
//   name: 'mean-spawn-1',
//   memory: 512,
//   vcpus: 1,
//   disk: 20,
//   locked: false,
//   status: 'active',
//   kernel: 
//    { id: 5175,
//      name: 'Ubuntu 14.04 x64 vmlinuz-3.13.0-57-generic',
//      version: '3.13.0-57-generic' },
//   created_at: '2016-04-30T07:30:27Z',
//   features: [ 'private_networking', 'virtio' ],
//   backup_ids: [],
//   next_backup_window: null,
//   snapshot_ids: [],
//   image: 
//    { id: 17075455,
//      name: 'mean-spawn-1-1462000309694',
//      distribution: 'Ubuntu',
//      slug: null,
//      public: false,
//      regions: [ 'sfo1' ],
//      created_at: '2016-04-30T07:12:18Z',
//      min_disk_size: 20,
//      type: 'snapshot',
//      size_gigabytes: 5.9 },
//   drives: [],
//   size: 
//    { slug: '512mb',
//      memory: 512,
//      vcpus: 1,
//      disk: 20,
//      transfer: 1,
//      price_monthly: 5,
//      price_hourly: 0.00744,
//      regions: 
//       [ 'ams1',
//         'ams2',
//         'ams3',
//         'fra1',
//         'lon1',
//         'nyc1',
//         'nyc2',
//         'nyc3',
//         'sfo1',
//         'sgp1',
//         'tor1' ],
//      available: true },
//   size_slug: '512mb',
//   networks: { v4: [ [Object], [Object] ], v6: [] },
//   region: 
//    { name: 'San Francisco 1',
//      slug: 'sfo1',
//      sizes: [ '32gb', '16gb', '2gb', '1gb', '4gb', '8gb', '512mb', '64gb', '48gb' ],
//      features: [ 'private_networking', 'backups', 'ipv6', 'metadata' ],
//      available: true },
//   tags: [] }
// { id: 14448832,
//   name: 'mean-spawn-2',
//   memory: 512,
//   vcpus: 1,
//   disk: 20,
//   locked: false,
//   status: 'active',
//   kernel: 
//    { id: 5175,
//      name: 'Ubuntu 14.04 x64 vmlinuz-3.13.0-57-generic',
//      version: '3.13.0-57-generic' },
//   created_at: '2016-04-30T22:55:27Z',
//   features: [ 'private_networking', 'virtio' ],
//   backup_ids: [],
//   next_backup_window: null,
//   snapshot_ids: [],
//   image: 
//    { id: 17075455,
//      name: 'mean-spawn-1-1462000309694',
//      distribution: 'Ubuntu',
//      slug: null,
//      public: false,
//      regions: [ 'sfo1' ],
//      created_at: '2016-04-30T07:12:18Z',
//      min_disk_size: 20,
//      type: 'snapshot',
//      size_gigabytes: 5.9 },
//   drives: [],
//   size: 
//    { slug: '512mb',
//      memory: 512,
//      vcpus: 1,
//      disk: 20,
//      transfer: 1,
//      price_monthly: 5,
//      price_hourly: 0.00744,
//      regions: 
//       [ 'ams1',
//         'ams2',
//         'ams3',
//         'fra1',
//         'lon1',
//         'nyc1',
//         'nyc2',
//         'nyc3',
//         'sfo1',
//         'sgp1',
//         'tor1' ],
//      available: true },
//   size_slug: '512mb',
//   networks: { v4: [ [Object], [Object] ], v6: [] },
//   region: 
//    { name: 'San Francisco 1',
//      slug: 'sfo1',
//      sizes: [ '32gb', '16gb', '2gb', '1gb', '4gb', '8gb', '512mb', '64gb', '48gb' ],
//      features: [ 'private_networking', 'backups', 'ipv6', 'metadata' ],
//      available: true },
//   tags: [] }
